#!/bin/bash

# Remove all branches, which have no remote on origin.
git-clean-no-remote () {
    git remote prune origin && git branch -vv | cut -c 3- | grep ': gone]' | awk '{print $1}' | xargs -n1 -r echo git branch -D
    read -p "Press enter to execute"
    git remote prune origin && git branch -vv | cut -c 3- | grep ': gone]' | awk '{print $1}' | xargs -n1 -r git branch -D
    git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}' | xargs -n1 -r echo git branch -d
    read -p "Press enter to execute"
    git branch -r | awk '{print $1}' | egrep -v -f /dev/fd/0 <(git branch -vv | grep origin) | awk '{print $1}' | xargs -n1 -r git branch -D
}
