#!/bin/bash

# start openshift cluster
oc-up () {
  HOSTNAME="localhost";
  OC_BASE_DIR="/var/lib/openshift";
  OC_VERSION="3.7";
  OC_CONFIG_DIR="/${OC_BASE_DIR}/${OC_VERSION}/config";
  OC_DATA_DIR="/${OC_BASE_DIR}/${OC_VERSION}/data";
  OC_PERSISTENT_VOLUMES="/${OC_BASE_DIR}/${OC_VERSION}/persistent";
  OC_VOLUMES_DIR="/${OC_BASE_DIR}/${OC_VERSION}/volumes";

  echo -e "${GREEN}Starting Openshift Origin ${OC_VERSION}${NC}";
  if [[ ! -d $OC_BASE_DIR/$OC_VERSION ]]; then
    USER=$(whoami);
    echo -e "${YELLOW}Creating working dir:${NC} ${OC_BASE_DIR}/${OC_VERSION}";
    sudo mkdir -p $OC_BASE_DIR/$OC_VERSION/$OC_CONFIG_DIR;
    sudo mkdir -p $OC_BASE_DIR/$OC_VERSION/$OC_DATA_DIR;
    sudo mkdir -p $OC_BASE_DIR/$OC_VERSION/$OC_PERSISTENT_VOLUMES;
    sudo chown -R $USER:$USER $OC_BASE_DIR;
  fi

  echo -e "${YELLOW}Using working dir:${NC} ${OC_BASE_DIR}/${OC_VERSION}";
  oc cluster up \
    --host-config-dir=$OC_CONFIG_DIR         \
    --host-data-dir=$OC_DATA_DIR             \
    --host-pv-dir=$OC_PERSISTENT_VOLUMES     \
    --host-volumes-dir=$OC_VOLUMES_DIR       \
    --public-hostname=$HOSTNAME              \
    --use-existing-config=true;

  # loosen security to allow for root being used in containers
  oc login -u system:admin;
  oc adm policy add-cluster-role-to-group sudoer system:authenticated developer;
  oc login -u developer;
  oc adm policy add-scc-to-group anyuid system:authenticated --as=system:admin;
}
