#!/bin/bash

reset_secutransfer () {
  docker exec -it secutransfer_mysql bash -c "mysql -u root -p%superUser2020! -e \"DROP DATABASE secutransfer; CREATE DATABASE secutransfer;\"" &&
  sed -i '/^ftapi.init.submitbox.template/d' ~/.ftapi/config/user-config.properties
  sed -i '/\.group/d' ~/.ftapi/config/user-config.properties
}
