# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias lgrep='grep -Ri --exclude-dir={node_modules,pub}'
# some more ls aliases
alias ll='ls -alF'
alias la='ls -A'
alias l='ls -CF'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

alias vim='nvim'

alias vpn='sudo openvpn *.ovpn'

alias q='exit'

# some aliases for git
alias gitc='git commit -p'
alias gitp='git push'
alias gitt='git log --all --decorate --oneline --graph'
alias gitb='git-create-branch'
alias gitd='git checkout development && git pull'

alias gitpr='git push -u origin HEAD && gh pr create --fill -l "ByteBusters" && gh pr merge --auto --squash && gh pr view --web'
alias gitlpr='gh pr list -A @me --web'
alias gitprf="gh pr list -R FTAPI-Software/Server-Secutransfer -l ByteBusters --state open --json 'number,mergeStateStatus,title,url' -t '{{range .}}{{(printf \"#%v\" .number | autocolor \"yellow\")}} {{hyperlink .url .title}} {{if (\"DIRTY\" | eq .mergeStateStatus) }}🛑{{else if (\"BLOCKED\" | eq .mergeStateStatus)}} {{(\"⏲ \" | autocolor \"green\")}} {{ else }}{{ .mergeStateStatus }}{{end}} {{\"\\n\"}}{{end}}'"

alias repos='cd ~/development;cd $(ls | fzf)'
alias update-pkg='sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo snap refresh'
# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# Tree
if [ ! -x "$(which tree 2>/dev/null)" ]
then
  alias tree="find . -not -path '*node_modules/*' -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
fi

alias port-usage='lsof -i'

alias kcfes='kubectl config use-context oidc@secutransfer-prod-fes1-1'
alias kcdbl='kubectl config use-context oidc@secutransfer-prod-dbl1-1'
alias kcdev='kubectl config use-context oidc@dev-cluster'
alias kcstaging='kubectl config use-context oidc@staging.fes.ftapi.com'

alias ftapi-yarn-validate='yarn test:unit & yarn lint:validate & yarn type-check'
alias ftapi-db-port-forward-0='kubectl -n percona-database port-forward cluster1-pxc-0 3306:3306'
alias ftapi-db-port-forward-1='kubectl -n percona-database port-forward cluster1-pxc-1 3306:3306'
alias ftapi-db-port-forward-2='kubectl -n percona-database port-forward cluster1-pxc-2 3306:3306'
alias ftapi-db-client='mysql --host=127.0.0.1 --port=3306 -u root -p'
alias ftapi-db-prod='k exec -n percona-database cluster1-pxc-1 -c pxc -it -- /bin/bash -c "mysql -uroot -p\$MYSQL_ROOT_PASSWORD"'
alias kf='k -n flux-system get kustomizations.kustomize.toolkit.fluxcd.io '
